# Generated by Django 4.2.3 on 2023-08-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="starwarscard",
            name="series_type",
            field=models.CharField(
                choices=[("B", "Blue"), ("R", "Red"), ("Y", "Yellow")], max_length=2
            ),
        ),
    ]
