# Generated by Django 4.2.3 on 2023-08-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0002_alter_starwarscard_series_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="starwarscard",
            name="condition",
        ),
        migrations.AddField(
            model_name="starwarscard",
            name="condition_type",
            field=models.CharField(
                choices=[
                    ("Mt", "Mint"),
                    ("Ex", "Excellent"),
                    ("Vg", "Very Good"),
                    ("Gd", "Good"),
                    ("Fr", "Fair"),
                    ("Pr", "Poor"),
                ],
                default="Gd",
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
