# Generated by Django 4.2.3 on 2023-08-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0004_appraisal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name="appraisal",
            options={"ordering": ["-appr_date"]},
        ),
        migrations.AlterField(
            model_name="appraisal",
            name="value",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="value ($)"
            ),
        ),
        migrations.AddField(
            model_name="starwarscard",
            name="characters",
            field=models.ManyToManyField(to="main_app.character"),
        ),
    ]
