# Generated by Django 4.2.3 on 2023-08-06 04:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0006_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="starwarscard",
            options={"ordering": ["card_number"]},
        ),
    ]
